### ISSUE TITLE
Instructions to build compiler container

### ISSUE THREAD

**Issue by gxgani** [jandelgado/lede-dockercompiler#3]
Hello!

I'm looking to build my own openwrt compiler container but with debian/ubuntu rootfs (similar to yours), any help is appreciated.

Thanks!

**Comment by jandelgado** [comment]
If I understand you right, you want the Docker Image with the builder to be based on Ubuntu?

That should be very easy. Currently the image uses Debian:
https://github.com/jandelgado/lede-dockercompiler/blob/b30a6b4377927b4085906534e463f2535efac7e3/docker/Dockerfile#L1

This must be changed to something like `FROM Ubuntu:18.04` and possibly the `apt-get install` part must be modified according to https://openwrt.org/docs/guide-developer/build-system/install-buildsystem (Check out the Ubuntu Section):

> sudo apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip

**Comment by jandelgado** [comment]
I just realized that I was working on changing the base image to ubuntu a few weeks ago. Will merge changes soon.
